### ISSUE TITLE
Paintable Fountain

### ISSUE THREAD

**Issue by PiggyWhiskey** [LatvianModder/LatBlocks#1]
First Issue :)
Love the mod, watched your youtube video.
Really needs some wiki information.

My Issue is, How do you set the liquid for the fountain? Can't Find any information whatsoever.

**Comment by LatvianModder** [comment]
Its a small tank (4000mB), you use pipes or something like that to pump fluid in and out. (bucket / fluid container rightclicking support will be added very soon). It also fills buckets, if you use hoppers to insert an empty bucket and eject a filled bucket.

**Comment by PiggyWhiskey** [comment]
Nice. Thank you for the quick response.
If you're up for feedback, keep reading. Otherwise feel free to ignore me.

Does the tank need to be 4 buckets? I didn't notice any impairment for less buckets (Less fountain, less "full")
I know you said you're working on right click action. How about WAILA? If there was a 0000mb/4000mb or something similar, it would give players an indication that it needs to be filled with liquid.
Block Rotation: It does stick out and bring attention to your blocks. But when its rotating in my hand, its a bit discerning. (Far from important)

**Comment by LatvianModder** [comment]
1) No, I needs at least 1 mB of any fluid, optionally a fluid that can be placed in world (most of them are, like Lava, Water, Destabilized Redstone etc.)
2) Waila is in my To-Do list, it will show smth like 1000 mB / 4000 mB of Water
3) Go in Start Screen > Mods > find LatCoreMC in the list > Config > set rotateBlocks to false. Ta-dah! I've thought of everything :smiley:

**Comment by PiggyWhiskey** [comment]
You have indeed. Nicely done. What I meant was, rather than 4 buckets. Just 1 bucket. 
Unless you might implement in the future larger raidius for more fluid.
